### PR TITLE
Updated botlist statuses

### PR DESCRIPTION
**Pull request by forgetfulskybro**

### CODE REVIEW

**Comment by Anonymous4078** [comment]
@forgetfulskybro Infinity Bot List and Rovel Discord List seems to be working again, please update the status.

**Comment by renhiyama** [comment]
https://tenor.com/view/stop-it-get-some-help-gif-15058124

**Review by mezotv — CHANGES_REQUESTED** [review]
Infinity and Rovel seem to work again

**Comment by forgetfulskybro** [comment]
Fixed Infinity & Rovel

**Review by mezotv — COMMENTED** [review]
Looks good!

**Comment by WhiteClueGaming** [comment]
@mezotv please change the red icon from Discordz

**Comment by mezotv** [comment]
Hey @WhiteClueGaming currently on vacation so it might take a bit until i will change it

**Pull request merged**
